language: node_js

node_js:
- stable

cache:
  yarn: false

addons:
  apt:
    config:
      retries: true

before_deploy: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
