language: node_js
node_js:
- stable

before_deploy:
- yarn build \
  && yarn generate-data
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
